import Foundation
import Testing
@testable import skyformac

struct GalleryLibraryModelsTests {
    @Test func favoritesAreCappedAtSix() {
        var library = GalleryLibrary()
        for _ in 0..<GalleryLibrary.maxFavorites {
            let added = library.addFavorite(UUID())
            #expect(added)
        }
        #expect(library.favoriteImageIDs.count == GalleryLibrary.maxFavorites)
        let overflowAdded = library.addFavorite(UUID())
        #expect(overflowAdded == false)
        #expect(library.favoriteImageIDs.count == GalleryLibrary.maxFavorites)
    }

    @Test func addingTheSameFavoriteTwiceIsANoOp() {
        var library = GalleryLibrary()
        let id = UUID()
        let firstAdd = library.addFavorite(id)
        let secondAdd = library.addFavorite(id)
        #expect(firstAdd)
        #expect(secondAdd == false)
        #expect(library.favoriteImageIDs == [id])
    }

    @Test func removingAFavoriteFreesUpASlot() {
        var library = GalleryLibrary()
        let id = UUID()
        library.addFavorite(id)
        library.removeFavorite(id)
        #expect(library.favoriteImageIDs.isEmpty)
        let readdedAfterRemoval = library.addFavorite(UUID())
        #expect(readdedAfterRemoval)
    }

    @Test func addImageToAlbumDoesNotDuplicate() {
        var library = GalleryLibrary()
        let album = GalleryAlbum(name: "M31")
        library.albums = [album]
        let imageID = UUID()
        library.addImage(imageID, toAlbum: album.id)
        library.addImage(imageID, toAlbum: album.id)
        #expect(library.albums.first?.imageIDs == [imageID])
    }

    @Test func removeImageFromAlbum() {
        var library = GalleryLibrary()
        let imageID = UUID()
        let album = GalleryAlbum(name: "M31", imageIDs: [imageID])
        library.albums = [album]
        library.removeImage(imageID, fromAlbum: album.id)
        #expect(library.albums.first?.imageIDs.isEmpty == true)
    }

    @Test func deletingAFolderDeletesItsAlbumsToo() {
        var library = GalleryLibrary()
        let folder = GalleryFolder(name: "Planets")
        let albumInFolder = GalleryAlbum(name: "Jupiter", parentFolderID: folder.id)
        let topLevelAlbum = GalleryAlbum(name: "M31")
        library.folders = [folder]
        library.albums = [albumInFolder, topLevelAlbum]
        library.deleteFolder(folder.id)
        #expect(library.folders.isEmpty)
        #expect(library.albums.map(\.name) == ["M31"])
    }

    @Test func albumsInFolderAreScopedToThatFolder() {
        var library = GalleryLibrary()
        let folder = GalleryFolder(name: "Planets")
        library.folders = [folder]
        library.albums = [
            GalleryAlbum(name: "Jupiter", parentFolderID: folder.id),
            GalleryAlbum(name: "M31", parentFolderID: nil),
        ]
        #expect(library.albums(inFolder: folder.id).map(\.name) == ["Jupiter"])
        #expect(library.albums(inFolder: nil).map(\.name) == ["M31"])
    }

    @Test func autoOrganizeReplacesOnlyPreviouslyAutoGeneratedAlbums() {
        var library = GalleryLibrary()
        let manualAlbum = GalleryAlbum(name: "My Favorites Session", isAutoGenerated: false)
        let staleAutoAlbum = GalleryAlbum(name: "Saturn", isAutoGenerated: true)
        library.albums = [manualAlbum, staleAutoAlbum]

        let imageID = UUID()
        library.autoOrganize(byObjectName: ["M31": [imageID]])

        #expect(library.albums.contains { $0.id == manualAlbum.id })
        #expect(!library.albums.contains { $0.name == "Saturn" })
        let newAlbum = library.albums.first { $0.name == "M31" }
        #expect(newAlbum?.isAutoGenerated == true)
        #expect(newAlbum?.imageIDs == [imageID])
    }

    @Test func autoOrganizePutsAnImageInEveryObjectAlbumItBelongsTo() {
        var library = GalleryLibrary()
        let imageID = UUID()
        library.autoOrganize(byObjectName: ["M31": [imageID], "M32": [imageID]])
        #expect(library.albums.first { $0.name == "M31" }?.imageIDs == [imageID])
        #expect(library.albums.first { $0.name == "M32" }?.imageIDs == [imageID])
    }
}
