import AppKit
import CoreGraphics
import CoreText
import Foundation

/// Stamps a small "AI - Sky For Mac" label into the bottom-right corner — applied only to an image
/// whose actual pixels were regenerated by an external AI model (`GeminiImageEnhancer`), never to
/// anything this app's own deterministic filters (`ImageEditor.render`, Magic Wand, Tikhonov, etc.)
/// produced, so a viewer can always tell which finishing touch actually happened to a shared image.
enum AIWatermark {
    /// `nil` if `image` has no pixels, or the watermarked copy couldn't be rendered.
    static func apply(to image: CGImage, text: String = "AI - Sky For Mac") -> CGImage? {
        guard image.width > 0, image.height > 0,
              let colorSpace = image.colorSpace ?? CGColorSpace(name: CGColorSpace.sRGB),
              let context = CGContext(
                  data: nil, width: image.width, height: image.height,
                  bitsPerComponent: 8, bytesPerRow: 0, space: colorSpace,
                  bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
              )
        else { return nil }
        // Same "draw the whole image into a same-size context, then draw more on top" pattern
        // `ThumbnailGenerator.makeThumbnail` already uses — `CGContext.draw` orients a `CGImage`
        // correctly on its own, no manual coordinate flip needed for this simple a composite.
        context.draw(image, in: CGRect(x: 0, y: 0, width: image.width, height: image.height))

        let fontSize = max(14, CGFloat(image.width) * 0.018)
        let font = CTFontCreateWithName("Helvetica-Bold" as CFString, fontSize, nil)
        let attributed = NSAttributedString(string: text, attributes: [
            .font: font,
            .foregroundColor: CGColor(red: 1, green: 1, blue: 1, alpha: 0.92),
        ])
        let line = CTLineCreateWithAttributedString(attributed)
        let bounds = CTLineGetBoundsWithOptions(line, .useOpticalBounds)

        let margin = fontSize * 0.8
        let padding = fontSize * 0.55
        let boxWidth = bounds.width + padding * 2
        let boxHeight = bounds.height + padding
        // `CGContext`'s own coordinate system is bottom-left-origin, y-up — placing the box near
        // `y = margin` really is the bottom of the image as drawn above, and "bottom-right" is
        // simply the box's own right edge sitting `margin` in from the image's own right edge.
        let boxOrigin = CGPoint(x: CGFloat(image.width) - boxWidth - margin, y: margin)
        let boxRect = CGRect(x: boxOrigin.x, y: boxOrigin.y, width: boxWidth, height: boxHeight)
        context.setFillColor(CGColor(red: 0, green: 0, blue: 0, alpha: 0.5))
        context.addPath(CGPath(roundedRect: boxRect, cornerWidth: 6, cornerHeight: 6, transform: nil))
        context.fillPath()

        context.textPosition = CGPoint(x: boxOrigin.x + padding, y: boxOrigin.y + (boxHeight - bounds.height) / 2 - bounds.origin.y)
        CTLineDraw(line, context)

        return context.makeImage()
    }
}
