import Foundation

/// A user-curated collection of elaborated images — the leaf node of the Gallery's own
/// Photos-style organization (a folder holds albums, an album holds images directly, matching
/// Apple Photos' own shape rather than the other way around). Images are referenced by
/// `ElaboratedImage.id` alone, not paired with a project id — those UUIDs are already unique
/// across the whole library, and resolving one back to its owning project/image happens once, at
/// render time, against the live project list, rather than keeping a second, potentially-stale
/// copy of image data in here.
struct GalleryAlbum: Codable, Identifiable, Equatable, Sendable {
    var id = UUID()
    var name: String
    var imageIDs: [UUID] = []
    /// `nil` means "at the top level," not inside any folder.
    var parentFolderID: UUID?
    /// Set only by "Auto-Organize" — lets a re-run replace exactly the albums it created last
    /// time without touching anything the user made or renamed by hand.
    var isAutoGenerated: Bool = false
}

/// A folder in the Gallery sidebar, holding albums — one level deep (a folder can't contain
/// another folder) as a deliberate scope cut from Apple Photos' own arbitrarily-nestable folders,
/// keeping "move this album to a folder" a single flat pick rather than a full tree navigator.
struct GalleryFolder: Codable, Identifiable, Equatable, Sendable {
    var id = UUID()
    var name: String
    var isAutoGenerated: Bool = false
}

/// The whole Gallery organization library — persisted as one `AppSettings.galleryLibrary` blob.
/// Scoped to the whole Gallery (every project's elaborated images), not any one project, matching
/// how the Gallery page itself already spans every project.
struct GalleryLibrary: Codable, Equatable, Sendable {
    var albums: [GalleryAlbum] = []
    var folders: [GalleryFolder] = []
    /// Ordered oldest-favorited-first, so the pinned row has a stable order rather than
    /// reshuffling every time the set changes.
    var favoriteImageIDs: [UUID] = []

    static let maxFavorites = 6

    func albums(inFolder folderID: UUID?) -> [GalleryAlbum] {
        albums.filter { $0.parentFolderID == folderID }.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }

    var rootFolders: [GalleryFolder] {
        folders.sorted { $0.name.localizedStandardCompare($1.name) == .orderedAscending }
    }

    @discardableResult
    mutating func addFavorite(_ imageID: UUID) -> Bool {
        guard !favoriteImageIDs.contains(imageID), favoriteImageIDs.count < Self.maxFavorites else { return false }
        favoriteImageIDs.append(imageID)
        return true
    }

    mutating func removeFavorite(_ imageID: UUID) {
        favoriteImageIDs.removeAll { $0 == imageID }
    }

    mutating func addImage(_ imageID: UUID, toAlbum albumID: UUID) {
        guard let index = albums.firstIndex(where: { $0.id == albumID }), !albums[index].imageIDs.contains(imageID) else { return }
        albums[index].imageIDs.append(imageID)
    }

    mutating func removeImage(_ imageID: UUID, fromAlbum albumID: UUID) {
        guard let index = albums.firstIndex(where: { $0.id == albumID }) else { return }
        albums[index].imageIDs.removeAll { $0 == imageID }
    }

    mutating func deleteAlbum(_ albumID: UUID) {
        albums.removeAll { $0.id == albumID }
    }

    /// Deleting a folder deletes the albums inside it too — matching Apple Photos' own behavior,
    /// since leaving those albums behind with a dangling `parentFolderID` would just make them
    /// invisible (no UI reads an unknown folder id as "top level") rather than actually gone.
    mutating func deleteFolder(_ folderID: UUID) {
        albums.removeAll { $0.parentFolderID == folderID }
        folders.removeAll { $0.id == folderID }
    }

    /// Replaces every previously auto-generated album with a fresh one per `groups` entry — never
    /// touches a user-created (or user-renamed-away-from-auto) album, so re-running this can't
    /// clobber manual organization. Each new album is a top-level album (not inside any folder),
    /// per this app's "one album per object name" auto-organize scope.
    mutating func autoOrganize(byObjectName groups: [String: [UUID]]) {
        albums.removeAll { $0.isAutoGenerated }
        for (name, imageIDs) in groups.sorted(by: { $0.key < $1.key }) {
            albums.append(GalleryAlbum(name: name, imageIDs: imageIDs, parentFolderID: nil, isAutoGenerated: true))
        }
    }
}
